version: '3.7'

services:
    db:
        image: postgres:12-alpine
        environment:
            POSTGRES_HOST_AUTH_METHOD: "trust"
        volumes:
            - postgres_data:/var/lib/postgresql/data/
    bot:
        build: .
        command: python rubbergod.py
        depends_on:
            - db

volumes:
    postgres_data:
